### ISSUE TITLE
User can submit a Youtube URL.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/youtube-album-ripper#1]
# Motivation

In order to get tracks sliced from an album, users must submit the album via a URL to the relevant Youtube video.

# Tasks

- [x] Create a homepage.
    - [x] Create index.html, styles.css, and main.js files with links
    - [x] Link to Bootstrap and create divs using the grid system to house the content
    - [x] Add a title to the webpage
    - [x] Add a bootstrap input form for receiving Youtube URLs
- [x] Build a working file server.
    - [x] Create an index.js file that requires Express and start listening on port 3000.
    - [x] Use Express.static to serve the relevant homepage files.
- [x] Handle the URL submission appropriately.
    - [x] Create event handler for POST requests to the server.
    - [x] Link form button hyperlink to fetch with method POST.
- [x] Verify that the sent URL is a link to a valid Youtube video.
    - [x] Scan the URL for the video id.
    - [x] Use only the video id when searching for the Youtube video.
    - [x] Verify that a Youtube video exists at the provided URL.

**Comment by danielduffield** [comment]
![screen shot 2017-07-11 at 1 25 24 pm](https://user-images.githubusercontent.com/29046343/28089018-7152e70a-663c-11e7-8633-fff70c5145fa.png)
