### ISSUE TITLE
User can delete a track from the tracklist.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/youtube-album-ripper#15]
# Motivation

While making a tracklist, users should be able to remove tracks that they don't want.

# Tasks

- [x] Create a function for removing one of the tracks and updating the track number of all subsequent tracks
- [x] Add to the createFormTable to append an additional column for the delete buttons
- [x] Add an event listener to find the target of the event i.e. which button was pressed and call the delete track function on that track number
- [x] Decrement currentTrack variable after deleting a track

**Comment by danielduffield** [comment]
![screen shot 2017-07-20 at 10 00 17 am](https://user-images.githubusercontent.com/29046343/28429677-6027e668-6d32-11e7-87da-fc71c0463d5a.png)
