### ISSUE TITLE
User can see an image corresponding to the Youtube video they select.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/youtube-album-ripper#17]
# Motivation

When a user submits a url, the image corresponding to that video should show above the video title for additional clarity.

# Tasks

- [x] Create a function for creating images using the Image constructor, setting the src to the saved album image in albumMetadata
- [x] Add image containers to each view
- [x] Append the image to each container

**Comment by danielduffield** [comment]
![screen shot 2017-07-20 at 2 08 13 pm](https://user-images.githubusercontent.com/29046343/28438983-eb77ab82-6d54-11e7-9dc0-90707538822f.png)
