### ISSUE TITLE
User can input time codes to slice a track.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/youtube-album-ripper#2]
# Motivation

Once a valid Youtube URL has been entered, users should be able to fill in information about the track they want to slice.

# Tasks

- [x] Use ytdl-core to get important video metadata
    - [x] Install ytdl-core
    - [x] Use ytdl-core to get the video title
    - [x] Use ytdl-core to get the length of the video
- [x] Build a Hashrouter to simulate a redirect once a Youtube URL has been submitted
    - [x] Remove the URL form once a valid URL has been submitted
    - [x] Display an error message if an invalid URL is submitted
- [x] Create a set of HTML elements that will be displayed if the URL is valid (for editing track info)
    - [x] Display a table with forms corresponding to track information
    - [x] Display the video title above the tracklist form
    - [x] Create a button to submit data in the track info forms
- [x] Install and use ffmpeg to take form inputs to slice a track
    - [x] Install fluent-ffmpeg as a dependency
    - [x] Create a function that uses keyData and submitted form data to slice the track
    - [x] Use this function within the form eventListener that is listening for tracklist submits
    - [x] Write sliced tracks to Downloaded folder on server in directory corresponding to Youtube Id

**Comment by danielduffield** [comment]
![screen shot 2017-07-11 at 3 18 52 pm](https://user-images.githubusercontent.com/29046343/28093478-4d69d6f4-664c-11e7-8d15-91738c703401.png)
