### ISSUE TITLE
User can slice multiple tracks from one album.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/youtube-album-ripper#3]
# Motivation

To increase the convenience of the app, users should be able to slice more than one track at once.

# Tasks

- [x] Add a button with an event listener that calls the addTrackForm function and increments the currentTrack
- [x] Refactor the transitionToTracklist function to make sure all tracks are cleared when the back button is used and a new url is submitted and that the currentTrack is reset
- [x] Loop through each track, calling sliceTrack for each in order to slice multiple tracks

**Comment by danielduffield** [comment]
![screen shot 2017-07-17 at 12 55 13 am](https://user-images.githubusercontent.com/29046343/28259335-a53891e4-6a8a-11e7-8d33-584e935cf3cb.png)
