### ISSUE TITLE
User can download one or more tracks.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/youtube-album-ripper#4]
# Motivation

Once the user has created and submitted a tracklist, download links for each individual track should appear to the right of each track form.

# Tasks

- [x] Create a function called getTrackLink that takes a track and creates an html link element with the href being the file location of the track
- [x] Use a function called renderTrackLink append the array of link elements corresponding to each track to the track forms
- [x] Create a function that constructs a new tracklist table to hold the finalized tracks
- [x] Hide the tracklist form table once tracks have been submitted
- [x] Append download links to the tracklist table
- [x] Create buttons for Start Over and Download All
- [x] Add event listeners for each button to return home and download all tracks respectively
- [x] Download archiver as a dependency
- [x] Create a function to make a zip folder containing the entire tracklist
- [x] Use the returned promise from compressing the tracklist as a response body to the sendTracklistPostRequest
- [x] Use a form combined with the download all button to provide a means for initiating the download
- [x] Set the download action attribute to the zip folder path returned in the response from the server
- [x] Add to the resetTracklist function so that the final tracklist is reset when the user chooses to start over and submit a new url request

**Comment by danielduffield** [comment]
![screen shot 2017-07-18 at 10 37 09 am](https://user-images.githubusercontent.com/29046343/28331220-18fb3d78-6ba5-11e7-83bd-0eb401cb9e72.png)
