### ISSUE TITLE
User can get album tracks without inputting time codes.

### ISSUE THREAD

**Issue by danielduffield** [danielduffield/youtube-album-ripper#5]
# Motivation

When users submit a youtube url link, they should have the option of loading all tracks using the description if available or pasting the timecodes into a form to autofill the tracklist.

# Tasks

- [x] Create a button that resets the tracklist
    - [x] Create a button that clears the inner html of the track form container, sets the current track 
        to one, and adds a single track form
- [x] Create a button that loads timecodes from Youtube description
    - [x] Create a function to parse a block of text to find track names and start times
    - [x] Create a function to determine track end times based on the start time of the next track
    - [x] Create a function to take a tracklist array of track objects and insert the data into the 
        tracklist table
- [x] Create a button that allows user to paste timecodes into a textarea
    - [x] Create a new view and hashchange corresponding to submitting timecodes
    - [x] Create a textarea element to hold a submitted tracklist
    - [x] Feed the textarea value into the function used to auto generate tracklists from video 
        descriptions
    - [x] Add two buttons, one to trigger the submit and one to cancel, taking the user back to the 
       tracklist

**Comment by danielduffield** [comment]
![screen shot 2017-07-19 at 9 23 42 am](https://user-images.githubusercontent.com/29046343/28378145-ff072e44-6c63-11e7-9459-371c82bd0ec8.png)

**Comment by danielduffield** [comment]
![screen shot 2017-07-19 at 10 22 37 am](https://user-images.githubusercontent.com/29046343/28380455-3ef3ce10-6c6c-11e7-9107-c41856fb20d1.png)
